src/commands/login/index.ts
src/store/db.ts

fixes pattern used to store the token, and to write to disk.
to read `db.get("config.token").value();`
https://github.com/typicode/lowdb/tree/v1.0.0/examples

corrects storing the token

---

src/store/db.ts

I just noticed that my conflict resolution didn't have the conclusion I was looking for.  It's fixed now 😎

fix merge that went horribly awry

---

src/lib/binaries.ts
src/lib/configs.ts

pulls latest builds, and disabled connecting to the blockchain

pull latest

---

.github/workflows/release.yml

updates package.json with release tag

update the version is package.json so we know whatis running

---

.github/workflows/release.yml

Reverts txlabs/blockless-cli#15

Revert "Update build version"

---

src/commands/wallet/index.ts
src/commands/wallet/list.ts
src/commands/wallet/remove.ts
src/index.ts

This adds function list with a table view to the CLI.

adds wallet list and wallet remove

---

src/commands/info/index.ts
src/commands/wallet/list.ts
src/index.ts

clean up info, fix wallet list

---

src/index.ts
yarn.lock

clean up the help command menu

---

src/commands/offchain/install.ts
src/commands/wallet/remove.ts
src/index.ts

these are some small fixes and adds `whoami`

some small fixes with whoami

---

src/index.ts

cleanup help menu according to spec

---

.github/workflows/test.yml

corrects failing test

---

src/commands/function/publish.ts
src/commands/function/shared.ts
src/index.ts

corrects publish with the build, leaves name as a required option (will change this later)
pathing prob needs help in publish

correct publish with build

---

src/commands/function/deploy.ts

corrects deploying the function to the console

creates a new deployment on the console

---

src/commands/function/publish.ts

need to give formData names, or will use tmp

corrects publishing with weird temp

---

src/commands/function/build.ts
src/commands/function/deploy.ts
src/commands/function/interfaces.ts
src/commands/function/publish.ts
src/commands/function/shared.ts
src/index.ts

commented out a bunch of stuff so help menus need to be redone, but cleaned up the executor a bit, and fixed publish, and deploy and build. Manifest is generated correctly.

cleanup some stuff, and fix publish, build

---

src/commands/function/deploy.ts
src/commands/function/init.ts
src/commands/function/list.ts
src/commands/function/publish.ts
src/commands/login/index.ts
src/index.ts
src/lib/help.ts
src/lib/npm.ts
src/lib/urls.ts
src/store/constants.ts

fixes an issue with login not referencing the correct server for the CLI.

fixes login and refactors some of the work done prior

---

src/commands/login/index.ts
src/index.ts

stores an auth token when passed to login

stores an auth token

---

src/commands/function/build.ts

adds ci to the cli always for build typescript

---

package.json
src/commands/function/init.ts
src/commands/function/interfaces.ts
src/lib/blsConfig.ts
src/lib/npm.ts
src/lib/randomName.ts
src/lib/utils.ts
yarn.lock

- Optimize function init command
- Add cli prompts input to override; name, compiler, template
- Generate bls.toml on function init

Generate bls.toml settings on function init

---

src/commands/function/list.ts

Handle relative widths for function list table columns, above 40

Handle relative widths for function list table columns, above 40

---

src/commands/self-update/index.ts
src/lib/binaries.ts

Include a fix to self-update to get latest download script from Git

Include a fix to self-update to get latest download script from Git

---

src/commands/function/delete.ts
src/commands/function/index.ts
src/commands/function/stop.ts

Include function stop and delete commands

Include function stop and delete commands

---

src/index.ts

Identify root level help menu request and fix the broken root help menu.

Prevent bad formatted help context menu

---

src/commands/sites/shared.ts

Bump the assembly script sdk and dependencies used within the sites bundler script

Update CLI sites bundler dependencies

---

package-lock.json
src/commands/offchain/index.ts
src/commands/offchain/install.ts
src/commands/offchain/start.ts
src/lib/binaries.ts
src/lib/keygen.ts

Networking layer and Runtime updated.

use the latest runtime to start

---

src/commands/function/build.ts
src/commands/function/interfaces.ts
src/lib/crypto.ts

fixes the problem where this was generating an archive, but then not putting in the checksum for the `tar.gz`

add support for archive download

---

src/commands/login/index.ts

supports both local host IPs when asking user to login.

add both IPs to the CLI

---

.github/workflows/release.yml

m1 are now available it github.

Update release.yml for new m1

---

src/commands/function/init.ts
src/commands/sites/frameworks.ts
src/lib/blsConfig.ts
src/prompts/function/init.ts

DRAFT: Added template init and prompts for javy typescript.

---

.github/workflows/test.yml
bin.js
dev-bin.js
package.json
src/index.ts
src/lib/npm.ts

removes some whines when moving to later version of NodeJS, increases minimum version needed.

updating min node version, and bash declare
